{
 "title": "lab08",
 "description": "add first suit of lab08 graphs",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Shows if service is up (1) or down (0)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"app\"}"
    }
   ]
  },
  {
   "title": "Status Code Distribution",
   "type": "piechart",
   "description": "Shows 2xx vs 4xx vs 5xx",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (status_code) (increase(http_requests_total{job=\"app\"}[5m]))",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "Active Requests ",
   "type": "gauge",
   "description": "Shows concurrent requests",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(http_requests_in_progress)", "legendFormat": "{{ label }}" }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "description": "Shows 5xx errors/sec",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=\"app\", status_code=~\"5..\"}[5m]))\r\n/\r\nsum(rate(http_requests_total{job=\"app\"}[5m]))",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "Request Duration p95",
   "type": "timeseries",
   "description": "Shows 95th percentile latency",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (le, endpoint) (rate(http_request_duration_seconds_bucket[5m]))\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Duration Heatmap",
   "type": "timeseries",
   "description": "Visualizes latency distribution",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "sum by (le) (rate(http_request_duration_seconds_bucket{endpoint=\"/health\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "description": "Shows requests/sec per endpoint",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (endpoint) (rate(http_requests_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}