{
 "title": "LAB08 dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Request Rate",
   "type": "timeseries",
   "description": "Shows requests/sec per endpoint",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[5m])) by (endpoint)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "description": "Shows 5xx errors/sec",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{status_code=~\"5..\"}[5m]))"
    }
   ]
  },
  {
   "title": "Request Duration p95",
   "type": "timeseries",
   "description": "hows 95th percentile latency",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Duration Heatmap",
   "type": "heatmap",
   "description": "Visualizes latency distribution",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_bucket[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Requests",
   "type": "gauge",
   "description": "Shows concurrent requests\n",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "http_requests_in_progress", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Shows if service is up (1) or down (0)",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"app\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status Code Distribution",
   "type": "piechart",
   "description": "Shows concurrent requests",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (status_code) (rate(http_requests_total[20m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}