{{- if .Values.statefulset.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "devops-info.fullname" . }}-headless
  labels:
    {{- include "devops-info.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "devops-info.selectorLabels" . | nindent 4 }}
{{- end }}
