---
- name: Restart app container
  shell: |
    docker stop "{{ app_container_name }}" || true
    docker rm "{{ app_container_name }}" || true
    docker run -d --name "{{ app_container_name }}" -p {{ app_port }}:5000 --restart unless-stopped "{{ docker_image }}:{{ docker_image_tag }}"
