---
- name: Restart app container
  community.docker.docker_container:
    name: "{{ app_container_name }}"
    image: "{{ app_image }}"
    state: started
    restart: true
    recreate: false
    pull: missing
    restart_policy: "{{ app_restart_policy }}"
    env_file: "{{ app_env_file_path }}"
    published_ports:
      - "{{ app_published_port }}:{{ app_port }}"
