linters-settings:
  gofmt:
    simplify: true

linters:
  disable-all: true
  enable:
    - gofmt
    - goimports

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-use-default: false
  exclude:
    - "should have a package comment"
    - "should have comment or be unexported"
    - "File is not `gofmt`-ed"
