---
# Common variables for all hosts
ansible_python_interpreter: /usr/bin/python3

# Docker configuration
docker_edition: ce
docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin

# Application configuration
app_name: devops-app
docker_image: 4hellboy4/devops-info-service
docker_tag: latest
app_port: 8000
app_internal_port: 8000
compose_project_dir: "/opt/{{ app_name }}"
docker_compose_version: "3.8"

# User configuration
deploy_user: ubuntu
