apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mychart.fullname" . }}-auth
type: Opaque
data:
  # Values must be base64 encoded
  username: {{ .Values.auth.username | b64enc | quote }}
  password: {{ .Values.auth.password | b64enc | quote }}

