replicaCount: 5

nameOverride: ""
fullnameOverride: ""

image:
  repository: netotveto/devops-app
  tag: "1.0.0"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  targetPort: 5000
  nodePort: 30080

podLabels:
  component: web

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000

containerSecurityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

env:
  - name: PORT
    value: "5000"
  - name: APP_VERSION
    value: "v2"

secret:
  enabled: true
  nameOverride: ""
  data:
    username: demo-user
    password: change-me

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "200m"
    memory: "256Mi"

livenessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 2
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 2
  failureThreshold: 3

autoscaling:
  enabled: false

ingress:
  enabled: false

httpRoute:
  enabled: false

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}

configMap:
  enabled: true
  mountPath: /config
  fileName: config.json
  envNameOverride: ""
  fileNameOverride: ""

appConfig:
  appName: devops-info-service
  environment: lab12
  featureFlags:
    visitsCounter: true
    configMapMount: true
    configMapEnv: true

appEnv:
  APP_ENV: lab12
  LOG_LEVEL: info
  FEATURE_VISITS_COUNTER: "true"
  FEATURE_CONFIGMAP_MOUNT: "true"
  FEATURE_CONFIGMAP_ENV: "true"

persistence:
  enabled: true
  mountPath: /data
  size: 100Mi
  storageClass: ""

vault:
  enabled: false
  role: ""
  secretPath: ""
  secretFile: config
  secretTemplate: |
    {{- with secret "secret/data/myapp/config" -}}
    username={{ .Data.data.username }}
    password={{ .Data.data.password }}
    {{- end -}}
