replicaCount: 1
app:
  name: "devops-app-dev"
  logLevel: "DEBUG"

image:
  tag: latest

service:
  type: NodePort
  nodePort: 30080

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi