{{- if and .Values.secrets.enabled .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "devops-python.secretName" . }}
  labels:
    {{- include "devops-python.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $k, $v := .Values.secrets.stringData }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}
