apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "devops-python.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "devops-python.labels" . | nindent 4 }}
