fullnameOverride: devops-info-python

replicaCount: 5

image:
  tag: "python"

resources:
  requests:
    memory: "64Mi"
    cpu: "50m"
  limits:
    memory: "128Mi"
    cpu: "100m"

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

persistence:
  enabled: false

vault:
  enabled: false

secrets:
  DB_USERNAME: "admin"
  DB_PASSWORD: "S3cur3P@ssw0rd"

rollout:
  enabled: true
  strategy: canary
  canary:
    steps:
      - setWeight: 20
      - pause: {}
      - setWeight: 40
      - pause: { duration: 30s }
      - setWeight: 60
      - pause: { duration: 30s }
      - setWeight: 80
      - pause: { duration: 30s }
      - setWeight: 100
