# values.yaml
replicaCount: 5

image:
  repository: reiterwurger/app
  tag: "v1"

environment: dev
logLevel: info

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: NodePort
  port: 80
  targetPort: 8080
  nodePort: 30080

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "200m"

# Здоровье приложения (согласно требованиям, не комментируем, а настраиваем)
livenessProbe:
  path: /health
  port: 8080
  initialDelaySeconds: 8
  periodSeconds: 5

readinessProbe:
  path: /health
  port: 8080
  initialDelaySeconds: 5
  periodSeconds: 5

rollout:
  enabled: false
  strategy: canary
  canary:
    steps:
      - setWeight: 20
      - pause: {}
      - setWeight: 40
      - pause:
          duration: 30s
      - setWeight: 60
      - pause:
          duration: 30s
      - setWeight: 80
      - pause:
          duration: 30s
      - setWeight: 100
  blueGreen:
    activeService: ""
    previewService: ""
    autoPromotionEnabled: false
    autoPromotionSeconds: 0
    previewServiceType: ClusterIP
    previewNodePort: null

statefulset:
  enabled: true
  serviceName: ""

persistence:
  enabled: true
  size: 100Mi
  storageClass: ""

appSecrets:
  username: "helm_user"
  password: "helm_password_placeholder"

