replicaCount: 5

environment: prod
logLevel: info


resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

service:
  type: LoadBalancer

livenessProbe:
  path: /health
  port: 8080
  initialDelaySeconds: 30
  periodSeconds: 5

readinessProbe:
  path: /health
  port: 8080
  initialDelaySeconds: 10
  periodSeconds: 3

persistence:
  enabled: true
  size: 1Gi
  storageClass: ""

statefulset:
  enabled: true
  serviceName: ""