apiVersion: v1
kind: Service
metadata:
  name: {{ include "devops-chart.fullname" . }}-service
  labels:
    {{- include "devops-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "devops-chart.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}