replicaCount: 3

nameOverride: ""
fullnameOverride: ""

image:
  repository: sergey173/app_python
  tag: "2026.04.09"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  targetPort: 5000
  nodePort: 30083

container:
  port: 5000

env:
  host: "0.0.0.0"
  port: "5000"
  debug: "False"
  releaseVersion: "v2"
  appEnv: "default"
  logLevel: "INFO"

configFile:
  appName: "devops-info-service"
  environment: "default"
  featureFlags:
    visitsCounter: true
    diagnostics: true
  settings:
    metricsEnabled: true
    jsonLogs: true

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1001

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "200m"

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0

livenessProbe:
  enabled: true
  httpGet:
    path: /health
    port: 5000
  initialDelaySeconds: 10
  periodSeconds: 5
  timeoutSeconds: 2
  failureThreshold: 3

readinessProbe:
  enabled: true
  httpGet:
    path: /health
    port: 5000
  initialDelaySeconds: 5
  periodSeconds: 3
  timeoutSeconds: 2
  failureThreshold: 3

hooks:
  image: busybox:1.36

  preInstall:
    enabled: true
    weight: -5
    deletePolicy: hook-succeeded

  postInstall:
    enabled: true
    weight: 5
    deletePolicy: hook-succeeded

secret:
  data:
    username: "change-me"
    password: "change-me"

serviceAccount:
  create: true
  name: "app-python-sa"

vault:
  enabled: false
  role: "app-python"
  secretPath: "secret/data/app-python/config"

persistence:
  enabled: true
  size: 100Mi
  storageClass: ""

rollout:
  enabled: false
  strategy: canary
  blueGreen:
    autoPromotionEnabled: false
    scaleDownDelaySeconds: 30

statefulset:
  enabled: true