---
- name: Wipe Web Application
  tags:
    - web_app_wipe
  when: web_app_wipe | bool
  block:

    - name: Stop And Remove Docker Compose Containers
      ansible.builtin.command: docker compose down
      args:
        chdir: /opt/{{ app_name }}
      failed_when: false
      changed_when: false

    - name: Remove Application Directory
      ansible.builtin.file:
        path: /opt/{{ app_name }}
        state: absent

    - name: Log Wipe Completion
      ansible.builtin.debug:
        msg: "Application {{ app_name }} wiped successfully"
