apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app-python.fullname" . }}-secret
  labels:
    {{- include "app-python.labels" . | nindent 4 }}
type: Opaque
stringData:
  SERVICE_NAME: {{ .Values.secrets.serviceName | quote }}
  API_KEY: {{ .Values.secrets.apiKey | quote }}
