# Lab 13 Task 3 — prod: manual sync only (no automated block)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-info-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/TsixPhoenix/DevOps-CC.git
    targetRevision: lab12
    path: lab12c/k8s/devops-info
    helm:
      valueFiles:
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
