{{- if and .Values.rollout.enabled .Values.rollout.analysis.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: {{ .Values.rollout.analysis.name }}
  labels:
    {{- include "devops-info-service.labels" . | nindent 4 }}
spec:
  metrics:
    - name: webcheck
      provider:
        web:
          url: http://{{ include "devops-info-service.fullname" . }}.{{ .Release.Namespace }}.svc:{{ .Values.service.port }}/health
          jsonPath: "{$.status}"
      successCondition: result == "healthy"
      interval: {{ .Values.rollout.analysis.interval }}
      count: {{ .Values.rollout.analysis.count }}
      failureLimit: {{ .Values.rollout.analysis.failureLimit }}
{{- end }}
