[webservers]
# Replace values below with your VM details from Lab 4
web-01 ansible_host=10.241.1.215 ansible_user=sevan ansible_ssh_private_key_file=~/.ssh/id_rsa

[webservers:vars]
ansible_python_interpreter=/usr/bin/python3
