# Replace with your VM IP and user from Lab 4
# Example: devops-lab4-vm ansible_host=84.201.xxx.xxx ansible_user=ubuntu
[webservers]
devops-lab4-vm ansible_host=89.169.129.134 ansible_user=ubuntu

[webservers:vars]
ansible_python_interpreter=/usr/bin/python3
