all:
  children:
    lab_servers:
      hosts:
        plumini:
          ansible_host: 62.84.119.211
          ansible_user: ubuntu
          ansible_python_interpreter: /usr/bin/python3
      vars:
        env: production
        region: ru-central1-a
