services:
  loki:
    image: grafana/loki:3.0.0
    container_name: loki
    command: -config.file=/etc/loki/config.yml
    ports:
      - "3100:3100"
    volumes:
      - ./loki/config.yml:/etc/loki/config.yml:ro
      - loki-data:/loki
    networks:
      - loki
    healthcheck:
      test: ["CMD-SHELL", "wget --quiet --tries=1 --output-document=- http://localhost:3100/ready || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: "0.5"
    restart: unless-stopped

  promtail:
    image: grafana/promtail:3.0.0
    container_name: promtail
    command: -config.file=/etc/promtail/config.yml
    ports:
      - "9080:9080"
    volumes:
      - ./promtail/config.yml:/etc/promtail/config.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    networks:
      - loki
    depends_on:
      loki:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: "0.25"
    restart: unless-stopped

  grafana:
    image: grafana/grafana:12.3.1
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - grafana-data:/var/lib/grafana
    networks:
      - loki
    env_file:
      - .env
    environment:
      - GF_SECURITY_ADMIN_USER=admin
    depends_on:
      loki:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget --quiet --tries=1 --output-document=- http://localhost:3000/api/health || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: "0.5"
    restart: unless-stopped

  app-python:
    build: ../app_python
    image: mashfeii/devops-info-service:latest
    container_name: app-python
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    networks:
      - loki
    labels:
      logging: "promtail"
      app: "devops-python"
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: "0.25"
    restart: unless-stopped

  app-go:
    image: mashfeii/devops-info-service-go:latest
    container_name: app-go
    ports:
      - "8001:8080"
    networks:
      - loki
    labels:
      logging: "promtail"
      app: "devops-go"
    deploy:
      resources:
        limits:
          memory: 64M
          cpus: "0.25"
    restart: unless-stopped

volumes:
  loki-data:
  grafana-data:

networks:
  loki:
    driver: bridge
