services:
  loki:
    image: grafana/loki:3.0.0
    command: -config.file=/etc/loki/config.yml
    ports:
      - 3100:3100
    volumes:
      - ./loki/config.yml:/etc/loki/config.yml:ro
      - loki-data:/loki
    networks:
      - logging

  promtail:
    image: grafana/promtail:3.0.0
    command: -config.file=/etc/promtail/config.yml
    ports:
      - 9080:9080
    volumes:
      - ./promtail/config.yml:/etc/promtail/config.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - logging
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:12.3.1
    ports:
      - 3000:3000
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_SECURITY_ALLOW_EMBEDDING=true
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - logging
    depends_on:
      - loki

  prometheus:
    image: prom/prometheus:v3.9.0
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    networks:
      - logging
    depends_on:
      - app-python

  app-python:
    image: danielambda/devops-app:latest
    ports:
      - 8000:8000
    environment:
      - PORT=8000
      - HOST=0.0.0.0
      - VISITS_FILE=/data/visits
    volumes:
      - app-python-data:/data
    networks:
      - logging
    labels:
      logging: "promtail"
      app: "devops-python"
    depends_on:
      - loki

volumes:
  loki-data:
  grafana-data:
  prometheus-data:
  app-python-data:

networks:
  logging:
    driver: bridge

