apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-info
  labels:
    app: devops-info
    app.kubernetes.io/name: devops-info
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: devops-core-course
spec:
  replicas: 3
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 600
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: devops-info
      app.kubernetes.io/name: devops-info
  template:
    metadata:
      labels:
        app: devops-info
        app.kubernetes.io/name: devops-info
        app.kubernetes.io/component: web
        app.kubernetes.io/part-of: devops-core-course
    spec:
      terminationGracePeriodSeconds: 30
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: devops-info
          image: sofiakulagina/devops-info:lab2
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 5002
              protocol: TCP
          env:
            - name: HOST
              value: "0.0.0.0"
            - name: PORT
              value: "5002"
            - name: APP_ENV
              value: "kubernetes"
            - name: APP_REVISION
              value: "v1"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          startupProbe:
            httpGet:
              path: /health
              port: http
            failureThreshold: 12
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: http
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: http
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
