grafana:
  defaultDashboardsTimezone: browser

alertmanager:
  enabled: true

prometheus:
  prometheusSpec:
    retention: 7d

kubeControllerManager:
  enabled: false

kubeScheduler:
  enabled: false

kubeEtcd:
  enabled: false
