apiVersion: v1
kind: Service
metadata:
  name: devops-info-service
  labels:
    app: devops-info
    app.kubernetes.io/name: devops-info
    app.kubernetes.io/component: web
spec:
  type: NodePort
  selector:
    app: devops-info
    app.kubernetes.io/name: devops-info
  ports:
    - name: http
      port: 80
      targetPort: http
      nodePort: 30082
      protocol: TCP
