apiVersion: v1
kind: Service
metadata:
  name: devops-info-python
  namespace: devops-lab9
  labels:
    app.kubernetes.io/name: devops-info-python
    app.kubernetes.io/part-of: devops-lab9
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: devops-info-python
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
      nodePort: 30080
