apiVersion: v1
kind: Service
metadata:
  name: devops-core-course-service
  labels:
    app: devops-core-course
spec:
  type: NodePort
  selector:
    app: devops-core-course
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30080
