nameOverride: ""
fullnameOverride: ""
replicaCount: 2
revisionHistoryLimit: 5
image:
  repository: devops-info-service-rust
  tag: lab10
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
  targetPort: http
  containerPort: 8080
strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0
env:
  port: "8080"
  rustLog: info
startupProbe:
  httpGet:
    path: /health
    port: http
  periodSeconds: 3
  timeoutSeconds: 2
  failureThreshold: 10
readinessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 3
  periodSeconds: 5
  timeoutSeconds: 2
  failureThreshold: 3
livenessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 2
  failureThreshold: 3
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi
podSecurityContext:
  seccompProfile:
    type: RuntimeDefault
containerSecurityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  runAsNonRoot: true
hooks:
  image:
    repository: busybox
    tag: "1.37.0"
    pullPolicy: IfNotPresent
  preInstall:
    enabled: true
    weight: -5
    deletePolicy:
      - before-hook-creation
      - hook-succeeded
  postInstall:
    enabled: true
    weight: 5
    deletePolicy:
      - before-hook-creation
      - hook-succeeded
    path: /health
    attempts: 30
    delaySeconds: 2
