apiVersion: v1
kind: Service
metadata:
  name: devops-info-headless
  labels:
    app: devops-info
spec:
  clusterIP: None
  selector:
    app: devops-info
  ports:
    - name: http
      port: 5000
      targetPort: 5000
