common_packages:
  - python3-pip
  - curl
  - git
  - vim
  - htop
  - ca-certificates
  - gnupg
  - lsb-release


common_set_timezone: true
common_timezone: "UTC"

# Added for lab06
deploy_user: devops
deploy_user_groups: [sudo, docker]
deploy_user_ssh_keys: []
