apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "devops-python-chart.fullname" . }}
  labels:
    {{- include "devops-python-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "devops-python-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "devops-python-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          env:
            {{- include "devops-python-chart.envVars" . | nindent 12 }}
          envFrom:
            - secretRef:
                name: {{ include "devops-python-chart.fullname" . }}-secret
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
  strategy:
    {{- if eq .Values.rollout.strategy "blueGreen" }}
    blueGreen:
      activeService: {{ include "devops-python-chart.fullname" . }}-service
      previewService: {{ include "devops-python-chart.fullname" . }}-preview
      autoPromotionEnabled: {{ .Values.rollout.blueGreen.autoPromotionEnabled }}
    {{- else }}
    canary:
      steps:
        - setWeight: 20
        - pause: {}
        - setWeight: 40
        - pause:
            duration: 30s
        - setWeight: 60
        - pause:
            duration: 30s
        - setWeight: 80
        - pause:
            duration: 30s
    {{- end }}
