apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-python.fullname" . }}-headless
  labels:
    {{- include "helm-python.labels" . | nindent 4 }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    {{- include "helm-python.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http