{{- if and (not .Values.statefulset.enabled) .Values.rollout.analysis.enabled (eq .Values.rollout.strategy "canary") }}
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
spec:
  metrics:
    - name: webcheck
      provider:
        web:
          url: http://{{ include "devops-service.name" . }}.default.svc/health
          jsonPath: "{$.status}"
      successCondition: result == "ok"
      interval: 10s
      count: 3
      failureLimit: 1
{{- end }}
