{{- if and .Values.rollout.enabled (eq .Values.rollout.strategy "canary") }}
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: {{ include "devops-info-service.fullname" . }}-success-rate
  labels:
    {{- include "devops-info-service.labels" . | nindent 4 }}
spec:
  metrics:
    - name: webcheck
      provider:
        web:
          url: http://{{ include "devops-info-service.fullname" . }}.{{ .Release.Namespace }}.svc:{{ .Values.service.port }}/health
          jsonPath: "{$.status}"
      successCondition: result == "ok"
      interval: 10s
      count: 3
      failureLimit: 1
{{- end }}
