{{- if .Values.hooks.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ include "devops-info-service.fullname" . }}-post-install"
  labels:
    {{- include "devops-info-service.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "{{ .Values.hooks.postInstall.weight }}"
    "helm.sh/hook-delete-policy": "{{ join "," .Values.hooks.postInstall.deletePolicy }}"
spec:
  template:
    metadata:
      labels:
        {{- include "devops-info-service.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      containers:
        - name: post-install-smoke-test
          image: "{{ .Values.hooks.image.repository }}:{{ .Values.hooks.image.tag }}"
          imagePullPolicy: {{ .Values.hooks.image.pullPolicy }}
          command:
            {{- tpl (toYaml .Values.hooks.postInstall.command) . | nindent 12 }}
{{- end }}
