apiVersion: batch/v1
kind: Job
metadata:
  name: preinstall-job
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      containers:
        - name: preinstall
          image: busybox
          command: ["sh", "-c", "echo Pre-install hook running"]
      restartPolicy: Never