{{- if .Values.rollout.enabled }}
{{- include "devops-info-service.persistenceValidation" . }}
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "devops-info-service.fullname" . }}
  labels:
    {{- include "devops-info-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  minReadySeconds: {{ .Values.minReadySeconds }}
  selector:
    matchLabels:
      {{- include "devops-info-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "devops-info-service.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
        {{- with .Values.commonLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        checksum/config-file: {{ tpl (.Files.Get "files/config.json") . | sha256sum }}
        checksum/config-env: {{ include "devops-info-service.configEnvData" . | sha256sum }}
        {{- if and .Values.secrets.enabled .Values.secrets.create }}
        checksum/secret: {{ toYaml .Values.secrets.data | sha256sum }}
        {{- end }}
        {{- if .Values.vault.enabled }}
        {{- include "devops-info-service.vaultAnnotations" . | nindent 8 }}
        {{- end }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "devops-info-service.serviceAccountName" . }}
      automountServiceAccountToken: {{ if .Values.vault.enabled }}true{{ else }}{{ .Values.automountServiceAccountToken }}{{ end }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "devops-info-service.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- include "devops-info-service.envVars" . | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "devops-info-service.envConfigMapName" . }}
          {{- if .Values.secrets.enabled }}
            - secretRef:
                name: {{ include "devops-info-service.secretName" . }}
          {{- end }}
          ports:
            - name: {{ .Values.container.portName }}
              containerPort: {{ .Values.container.port }}
              protocol: TCP
          volumeMounts:
            - name: config-volume
              mountPath: {{ .Values.config.mountPath }}
              readOnly: true
            - name: data-volume
              mountPath: {{ .Values.persistence.mountPath }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.probes.startup.enabled }}
          startupProbe:
            {{- toYaml (omit .Values.probes.startup "enabled") | nindent 12 }}
          {{- end }}
          {{- if .Values.probes.liveness.enabled }}
          livenessProbe:
            {{- toYaml (omit .Values.probes.liveness "enabled") | nindent 12 }}
          {{- end }}
          {{- if .Values.probes.readiness.enabled }}
          readinessProbe:
            {{- toYaml (omit .Values.probes.readiness "enabled") | nindent 12 }}
          {{- end }}
          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "devops-info-service.configFileConfigMapName" . }}
        - name: data-volume
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "devops-info-service.pvcName" . }}
          {{- else }}
          emptyDir: {}
          {{- end }}
  strategy:
    {{- if eq .Values.rollout.strategy "blueGreen" }}
    blueGreen:
      activeService: {{ include "devops-info-service.fullname" . }}
      previewService: {{ include "devops-info-service.previewServiceName" . }}
      autoPromotionEnabled: {{ .Values.rollout.blueGreen.autoPromotionEnabled }}
      {{- if gt (int .Values.rollout.blueGreen.autoPromotionSeconds) 0 }}
      autoPromotionSeconds: {{ .Values.rollout.blueGreen.autoPromotionSeconds }}
      {{- end }}
    {{- else }}
    canary:
      maxSurge: {{ .Values.rollout.canary.maxSurge | quote }}
      maxUnavailable: {{ .Values.rollout.canary.maxUnavailable | quote }}
      steps:
        - setWeight: 20
        - pause: {}
        {{- if .Values.rollout.analysis.enabled }}
        - analysis:
            templates:
              - templateName: {{ include "devops-info-service.analysisTemplateName" . }}
        {{- end }}
        - setWeight: 40
        - pause:
            duration: 30s
        - setWeight: 60
        - pause:
            duration: 30s
        - setWeight: 80
        - pause:
            duration: 30s
        - setWeight: 100
    {{- end }}
{{- end }}
