apiVersion: v1
kind: Secret
metadata:
  name: {{ include "devops-service.name" . }}-secret
  labels:
    {{- include "devops-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.secrets.username }}
  password: {{ .Values.secrets.password }}