{{- if .Values.credentialsSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "devops-info-service.credentialsSecretName" . }}
  labels:
    {{- include "devops-info-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.credentialsSecret.stringData.username | quote }}
  password: {{ .Values.credentialsSecret.stringData.password | quote }}
{{- end }}
