{{- if and .Values.rollout.enabled .Values.rollout.analysis.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: {{ include "common.fullname" . }}-healthcheck
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  metrics:
    - name: healthcheck
      interval: {{ .Values.rollout.analysis.interval }}
      count: {{ .Values.rollout.analysis.count }}
      failureLimit: {{ .Values.rollout.analysis.failureLimit }}
      successCondition: {{ .Values.rollout.analysis.successCondition | quote }}
      provider:
        web:
          url: {{ default (printf "http://%s.%s.svc:%v/health" (include "common.fullname" .) .Release.Namespace .Values.service.port) .Values.rollout.analysis.url | quote }}
          jsonPath: "{$.status}"
{{- end }}
