{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "devops-info.secretName" . }}
  labels:
    {{- include "devops-info.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key := keys .Values.secrets.data | sortAlpha }}
  {{ $key }}: {{ index $.Values.secrets.data $key | quote }}
  {{- end }}
{{- end }}
