{{- if and (eq .Values.workload.type "statefulset") .Values.headlessService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "devops-info.headlessServiceName" . }}
  labels:
    {{- include "devops-info.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    {{- include "devops-info.selectorLabels" . | nindent 4 }}
{{- end }}
