{{- if .Values.statefulset.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "common-lib.fullname" . }}
  labels:
    {{- include "devops-info.deploymentLabels" . | nindent 4 }}
spec:
  serviceName: {{ include "devops-info.headlessServiceName" . }}
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  minReadySeconds: {{ .Values.minReadySeconds }}
  podManagementPolicy: {{ .Values.statefulset.podManagementPolicy }}
  updateStrategy:
    type: {{ .Values.statefulset.updateStrategy.type }}
    {{- if and (eq .Values.statefulset.updateStrategy.type "RollingUpdate") .Values.statefulset.updateStrategy.rollingUpdate (hasKey .Values.statefulset.updateStrategy.rollingUpdate "partition") }}
    rollingUpdate:
      partition: {{ .Values.statefulset.updateStrategy.rollingUpdate.partition }}
    {{- end }}
  selector:
    matchLabels:
      {{- include "common-lib.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "devops-info.deploymentLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- $vaultAnnotations := include "devops-info.vaultAnnotations" . }}
      annotations:
        checksum/config-file: {{ .Files.Get (printf "files/%s" .Values.configMap.fileName) | sha256sum }}
        checksum/config-env: {{ toJson .Values.env | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if $vaultAnnotations }}
        {{- $vaultAnnotations | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "devops-info.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      securityContext:
        {{- include "common-lib.podSecurityContext" .Values.securityContext.pod | nindent 8 }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "devops-info.fileConfigMapName" . }}
        {{- if not .Values.persistence.enabled }}
        - name: data-volume
          emptyDir: {}
        {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "devops-info.envConfigMapName" . }}
            - secretRef:
                name: {{ include "devops-info.secretName" . }}
          volumeMounts:
            - name: config-volume
              mountPath: {{ .Values.configMap.mountPath }}
              readOnly: true
            - name: data-volume
              mountPath: {{ .Values.persistence.mountPath }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.probes.startup.enabled }}
          startupProbe:
            {{- include "common-lib.httpProbe" .Values.probes.startup | nindent 12 }}
          {{- end }}
          {{- if .Values.probes.liveness.enabled }}
          livenessProbe:
            {{- include "common-lib.httpProbe" .Values.probes.liveness | nindent 12 }}
          {{- end }}
          {{- if .Values.probes.readiness.enabled }}
          readinessProbe:
            {{- include "common-lib.httpProbe" .Values.probes.readiness | nindent 12 }}
          {{- end }}
          securityContext:
            {{- include "common-lib.containerSecurityContext" .Values.securityContext.container | nindent 12 }}
  {{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: data-volume
        labels:
          {{- include "devops-info.baseLabels" . | nindent 10 }}
          app.kubernetes.io/component: "storage"
      spec:
        accessModes:
          {{- range .Values.persistence.accessModes }}
          - {{ . }}
          {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
        {{- with .Values.persistence.storageClass }}
        storageClassName: {{ . | quote }}
        {{- end }}
  {{- end }}
{{- end }}
