nameOverride: ""
fullnameOverride: ""

replicaCount: 2

image:
  repository: nginxdemos/hello
  tag: "plain-text"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 80

containerPort: 80

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

probes:
  liveness:
    httpGet:
      path: /
      port: http
    initialDelaySeconds: 10
    periodSeconds: 10
  readiness:
    httpGet:
      path: /
      port: http
    initialDelaySeconds: 3
    periodSeconds: 5