{
 "title": "Lab07 - Monitoring",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Log Level Distribution",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (level) (count_over_time({app=~\"devops-.*\"} | json | __error__=\"\" [5m]))"
    }
   ]
  },
  {
   "title": "Request Rate by App",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (app) (rate({app=~\"devops-.*\"}[1m]))"
    }
   ]
  },
  {
   "title": "Error Logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=~\"devops-.*\"} | json | __error__=\"\" | level=~\"WARNING|ERROR\""
    }
   ]
  },
  {
   "title": "JSON parse + method filter",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=\"devops-python\"} | json | __error__=\"\" | method=\"GET\""
    }
   ]
  },
  {
   "title": "All Application Logs",
   "type": "logs",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=~\"devops-.*\"}"
    }
   ]
  }
 ]
}