{{- if and (eq .Values.workload.kind "Rollout") .Values.rollout.canary.analysis.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: {{ include "devops-info-service.fullname" . }}-health-check
  labels:
    {{- include "devops-info-service.labels" . | nindent 4 }}
spec:
  metrics:
    - name: health-endpoint
      interval: {{ .Values.rollout.canary.analysis.interval }}
      count: {{ .Values.rollout.canary.analysis.count }}
      failureLimit: {{ .Values.rollout.canary.analysis.failureLimit }}
      successCondition: {{ .Values.rollout.canary.analysis.successCondition | quote }}
      provider:
        web:
          url: http://{{ include "devops-info-service.serviceName" . }}.{{ .Release.Namespace }}.svc{{ .Values.rollout.canary.analysis.path }}
          jsonPath: {{ .Values.rollout.canary.analysis.jsonPath | quote }}
{{- end }}
