replicaCount: 1

image:
  repository: chaleshka/devops-info-service
  pullPolicy: IfNotPresent
  tag: "latest"

env:
  - name: HOST
    value: "0.0.0.0"
  - name: PORT
    value: "5000"

nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  port: 80
  targetPort: 5000
  nodePort: 30088

strategy:
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

livenessProbe:
  httpGet:
    path: /health
    port: 5000
  initialDelaySeconds: 5
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /health
    port: 5000
  initialDelaySeconds: 5
  periodSeconds: 5

secret:
  appUsername: "chal"
  appPassword: "password_for_DevOps"