{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "python-app.secretName" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $name, $value := .Values.secret.data }}
  {{ $name }}: {{ $value | quote }}
  {{- end }}
{{- end }}
