apiVersion: v1
kind: Secret
metadata:
  name: {{ include "python-app.fullname" . }}-secret
  labels:
    {{- include "python-app.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ include "python-app.name" . }}
    monitoring: enabled
type: Opaque
stringData:
  API_KEY: {{ .Values.secrets.apiKey | default "change-me" }}
  DB_PASSWORD: {{ .Values.secrets.dbPassword | default "change-me" }}
  ADMIN_PASSWORD: {{ .Values.secrets.adminPassword | default "change-me" }}