replicaCount: 2

image:
  tag: latest

service:
  type: ClusterIP
  nodePort: null

resources:
  requests:
    cpu: 150m
    memory: 192Mi
  limits:
    cpu: 300m
    memory: 384Mi

env:
  RELEASE_TRACK: prod

appConfig:
  environment: prod
  logLevel: info
  features:
    visitsCounter: "true"
    configHotReload: "true"

persistence:
  size: 1Gi

vault:
  enabled: true

livenessProbe:
  initialDelaySeconds: 20
  periodSeconds: 5

readinessProbe:
  initialDelaySeconds: 8
  periodSeconds: 4
