# Production environment overrides.
# Usage: helm install python-app-prod ./k8s/python-app -f k8s/python-app/values-prod.yaml

replicaCount: 5

image:
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  targetPort: 5000
  nodePort: 30082

resources:
  requests:
    cpu: "200m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

env:
  - name: ENV
    value: "production"

environment: "production"
logLevel: "INFO"
appName: "devops-info-service"

livenessProbe:
  httpGet:
    path: /health
    port: 5000
  initialDelaySeconds: 30
  periodSeconds: 5
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /health
    port: 5000
  initialDelaySeconds: 10
  periodSeconds: 3
  failureThreshold: 3
