# Blue-green rollout overrides for Lab 14.

replicaCount: 4

workload:
  type: rollout

service:
  type: NodePort
  port: 80
  targetPort: 5000
  nodePort: 30081

environment: "bluegreen"
logLevel: "INFO"
appName: "devops-info-service-bluegreen"

rollout:
  strategy: blueGreen
  blueGreen:
    autoPromotionEnabled: false
    previewServiceType: ClusterIP
