workload:
  type: statefulset

initContainers:
  enabled: true
  download:
    enabled: true
    image: busybox:1.36
    url: https://example.com
    fileName: index.html
  waitForService:
    enabled: true
    image: busybox:1.36
    host: kubernetes.default.svc.cluster.local
    intervalSeconds: 2
