---
# Python app deployment variables
# Used by playbooks/deploy_python.yml

# Application identity
app_name: devops-python
docker_image: "112005/devops-lab3-python"
docker_tag: latest

# Port mapping: host:5000 -> container:8080 (gunicorn)
app_port: 5000
app_internal_port: 8080

# Docker Compose project directory
compose_project_dir: "/opt/{{ app_name }}"

# Restart policy
app_restart_policy: unless-stopped
