---
# Python app deployment variables
app_name: devops-python
docker_image: blxxdclxud/devops-info-service
docker_tag: latest
app_port: 5000
app_internal_port: 5000
compose_project_dir: "/opt/devops-python"
