server.address=${HOST:0.0.0.0}
server.port=${PORT:8080}

# Make 404s throw NoHandlerFoundException so we can return JSON consistently.
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false

