replicaCount: 3

image:
  repository: kosmogor/devops
  tag: latest
  pullPolicy: IfNotPresent 

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext:
  allowPrivilegeEscalation: false
  runAsNonRoot: true
  runAsUser: 1000
  capabilities:
    drop: ["ALL"]

service:
  type: NodePort
  port: 80
  targetPort: 8000
  nodePort: 30000

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  requests:
    memory: "64Mi"
    cpu: "100m"
  limits:
    memory: "128Mi"
    cpu: "200m"

livenessProbe:
  enabled: true
  path: /health
  port: 8000
  initialDelaySeconds: 15
  periodSeconds: 10
  timeoutSeconds: 3
  failureThreshold: 3

readinessProbe:
  enabled: true
  path: /health
  port: 8000
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 2
  successThreshold: 1

hooks:
  enabled: true
  validation:
    enabled: true
  smokeTest:
    enabled: true
  notification:
    enabled: true

config:
  mountPath: /config
  file:
    appName: "devops-info"
    environment: "development"
    featureFlags:
      visitsCounter: true
      metrics: true
  env:
    data:
      APP_NAME: "devops-info-service"
      APP_ENV: "development"
      LOG_LEVEL: "info"

env:
  DEBUG: "false"

persistence:
  enabled: true
  mountPath: /data
  size: 100Mi
  storageClass: ""

secrets:
  username: "dev-username"
  password: "dev-password"

vault:
  enabled: true
  role: "devops-info-vault"
  secretPath: "secret/data/devops-info/config"
  template: |
    {{- with secret "secret/data/devops-info/config" -}}
    username={{ .Data.data.username }}
    password={{ .Data.data.password }}
    {{- end -}}

rollout:
  enabled: false
  strategy: "canary"
  revisionHistoryLimit: 3
  canary:
    maxSurge: 1
    maxUnavailable: 0
  blueGreen:
    autoPromotionEnabled: false
    previewReplicaCount: 1
    scaleDownDelaySeconds: 30

statefulset:
  enabled: true
  podManagementPolicy: OrderedReady
  revisionHistoryLimit: 3
  updateStrategy:
    type: RollingUpdate
    partition: 2

nodeSelector: {}

tolerations: []

affinity: {}

podAntiAffinity: {}