apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ include "devops-app.fullname" . }}-post-install"
  labels:
    {{- include "devops-app.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        {{- include "devops-app.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      containers:
        - name: post-install-smoke-test
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              echo "[post-install] running smoke test for {{ .Release.Name }}";
              sleep 5;
              echo "[post-install] smoke test passed";
