---
- name: Deploy All Applications
  hosts: webservers
  become: true

  tasks:
    - name: Deploy Python App
      ansible.builtin.include_role:
        name: web_app
      vars:
        app_name: devops-python
        docker_image: blxxdclxud/devops-info-service
        docker_tag: latest
        app_port: 5000
        app_internal_port: 5000
        compose_project_dir: /opt/devops-python

    - name: Deploy Bonus App
      ansible.builtin.include_role:
        name: web_app
      vars:
        app_name: devops-bonus
        docker_image: blxxdclxud/devops-info-service
        docker_tag: latest
        app_port: 8001
        app_internal_port: 5000
        compose_project_dir: /opt/devops-bonus
