---
- name: Deploy application
  hosts: webservers
  become: true
  pre_tasks:
    - name: Load deployment variables from vault file
      ansible.builtin.include_vars:
        file: ../group_vars/all.yml
      no_log: true
  roles:
    - role: web_app
      tags:
        - web_app
