env:
  - name: HOST
    value: "0.0.0.0"
  - name: PORT
    value: "5000"
  - name: SERVICE_NAME
    value: "devops-info-service-dev"
  - name: SERVICE_VERSION
    value: "1.1.0-dev"
  - name: SERVICE_DESCRIPTION
    value: "Development deployment of the Python DevOps Info Service"
  - name: RELEASE_TRACK
    value: "dev-green-v2"

config:
  application:
    name: "devops-info-service-dev"
    environment: "dev"
    description: "Development deployment of the Python DevOps Info Service"
  env:
    APP_ENV: "dev"
    LOG_LEVEL: "DEBUG"
  settings:
    releaseTrack: "dev-green-v2"
