replicaCount: 3

image:
  repository: abrahambarrett228/lab02
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  targetPort: 5000
  nodePort: 30560

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

probes:
  liveness:
    path: /health
    initialDelaySeconds: 10
    periodSeconds: 10
  readiness:
    path: /health
    initialDelaySeconds: 5
    periodSeconds: 5

secrets:
  username: "admin"
  password: "changeme"

persistence:
  enabled: true
  size: 100Mi
  storageClass: ""

statefulset:
  enabled: false
  updateStrategy: RollingUpdate
  partition: 0

rollout:
  strategy: canary
  analysis:
    enabled: false
    interval: 10s
    count: 3
    failureLimit: 1