replicaCount: 3

image:
  repository: mararokkel/devops-info-service
  tag: latest
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

credentials:
  enabled: true
  username: "lab-user"
  password: "lab-password-placeholder"

serviceAccount:
  create: true
  name: ""

vaultInjection:
  enabled: false
  role: devops-info-service
  secretPath: secret/data/devops-info/config
  secretAlias: config

config:
  fileMountPath: /config
  env:
    APP_NAME: devops-info-service
    APP_ENV: dev
    LOG_LEVEL: info

persistence:
  enabled: false
  size: 100Mi
  storageClass: ""
  mountPath: /data
  fileName: visits

podAnnotations: {}

podLabels: {}

podSecurityContext:
  fsGroup: 1000

service:
  type: NodePort
  port: 80
  targetPort: 5000
  nodePort: 30080

resources:
  limits:
    cpu: 300m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0

env:
  - name: HOST
    value: "0.0.0.0"
  - name: PORT
    value: "5000"
  - name: LAB9_UPDATE_ID
    value: "v4"

livenessProbe:
  httpGet:
    path: /health
    port: 5000
  initialDelaySeconds: 10
  periodSeconds: 5
  timeoutSeconds: 2
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /health
    port: 5000
  initialDelaySeconds: 5
  periodSeconds: 3
  timeoutSeconds: 2
  failureThreshold: 3

hooks:
  deleteAfterSuccess: true
  preInstall:
    image: busybox:1.36
  postInstall:
    image: curlimages/curl:8.5.0
