replicaCount: 1

image:
  tag: "1.0.0"

env:
  appName: devops-info-service
  appEnv: development
  appRegion: lab12-dev
  logLevel: debug

config:
  responseMode: detailed

service:
  type: NodePort
  nodePort: 30080

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi

probes:
  startup:
    failureThreshold: 10
    periodSeconds: 4
  liveness:
    periodSeconds: 15
  readiness:
    initialDelaySeconds: 2
    periodSeconds: 4
