apiVersion: v1
kind: Secret
metadata:
  name: {{ include "devops-app.fullname" . }}-credentials
  labels:
    {{- include "devops-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_USERNAME: {{ .Values.secrets.dbUsername | quote }}
  DB_PASSWORD: {{ .Values.secrets.dbPassword | quote }}
secrets:
  dbUsername: "admin"
  dbPassword: "supersecret123"