apiVersion: v1
kind: Service
metadata:
  name: {{ if and (eq .Values.workload.type "rollout") (eq .Values.rollout.strategy "blueGreen") }}{{ .Values.rollout.blueGreen.activeService | default (printf "%s-active" (include "devops-app.fullname" .)) }}{{ else }}{{ include "devops-app.fullname" . }}{{ end }}
  labels:
    {{- include "devops-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "devops-app.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      {{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
{{- if and (eq .Values.workload.type "rollout") (eq .Values.rollout.strategy "blueGreen") }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.rollout.blueGreen.previewService | default (printf "%s-preview" (include "devops-app.fullname" .)) }}
  labels:
    {{- include "devops-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: preview
spec:
  type: ClusterIP
  selector:
    {{- include "devops-app.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
{{- end }}
{{- if and (eq .Values.workload.type "statefulset") (.Values.service.headless.enabled) }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.headless.name | default (printf "%s-headless" (include "devops-app.fullname" .)) }}
  labels:
    {{- include "devops-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: headless
spec:
  clusterIP: None
  selector:
    {{- include "devops-app.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
{{- end }}