---
- name: restart application container
  community.docker.docker_container:
    name: "{{ app_container_name }}"
    image: "{{ docker_image }}:{{ docker_image_tag }}"
    state: started
    restart_policy: "{{ restart_policy }}"
    published_ports:
      - "{{ app_port }}:{{ app_port }}"
    env:
      "{{ env_vars }}"
    recreate: yes