---
- name: restart app container
  community.docker.docker_container:
    name: "{{ app_container_name }}"
    state: started
  when: app_container_restart is defined and app_container_restart | default(false) | bool
