# Blue-green rollout profile (Lab 14 Task 3)
# Usage: helm upgrade --install <release> k8s/devops-python -f values-bluegreen.yaml -n <ns>

rollout:
  strategy: blueGreen
  blueGreen:
    autoPromotionEnabled: false
    previewService:
      enabled: true
      nodePort: 30084

replicaCount: 2

image:
  repository: devops-python
  tag: "bg-v1"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  targetPort: 5000
  nodePort: 30083

resources:
  requests:
    memory: "64Mi"
    cpu: "50m"
  limits:
    memory: "128Mi"
    cpu: "100m"

livenessProbe:
  enabled: true
  httpGet:
    path: /health
    port: 5000
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 2
  failureThreshold: 3

readinessProbe:
  enabled: true
  httpGet:
    path: /health
    port: 5000
  initialDelaySeconds: 3
  periodSeconds: 5
  timeoutSeconds: 1
  failureThreshold: 2

app:
  name: devops-info-service-blue
  environment: dev-bluegreen
  env:
    APP_ENV: blue
    LOG_LEVEL: debug
    FEATURE_VISITS_COUNTER: "true"
    FEATURE_METRICS: "true"

hooks:
  preInstall:
    enabled: false
  postInstall:
    enabled: false
