apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-info-python
  labels:
    app: devops-info-python
    app.kubernetes.io/name: devops-info-python
    app.kubernetes.io/component: backend
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: devops-info-python
  template:
    metadata:
      labels:
        app: devops-info-python
        app.kubernetes.io/name: devops-info-python
        app.kubernetes.io/component: backend
    spec:
      containers:
        - name: app
          image: tsixphoenix/devops-info-python:lab9
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 5000
          env:
            - name: HOST
              value: "0.0.0.0"
            - name: PORT
              value: "5000"
            - name: RELEASE_ID
              value: "v2"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            runAsUser: 10001
