FROM python:3.11.8-slim-bookworm

RUN useradd --create-home --shell /bin/bash appuser

WORKDIR /app

COPY requirements.txt .

RUN pip install --trusted-host pypi.yandex.ru -i https://pypi.yandex.ru/simple/ --no-cache-dir -r requirements.txt

COPY app.py .

USER appuser

EXPOSE 5000

CMD [ "python", "app.py" ]
