apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-info-service-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/pavorkmertt/DevOps-Core-Course.git
    targetRevision: lab12
    path: k8s/devops-info-service
    helm:
      releaseName: lab13-dev
      valueFiles:
        - values-dev.yaml
      values: |
        replicaCount: 1
        service:
          type: NodePort
          nodePort: 30090
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
