apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-app-prod
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: devops-lab14
    environment: prod
spec:
  project: default
  source:
    repoURL: https://github.com/ellilin/DevOps.git
    targetRevision: lab14
    path: k8s/python-app
    helm:
      releaseName: python-app-prod
      valueFiles:
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
