apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-app
  namespace: argocd
  labels:
    app.kubernetes.io/name: python-app
    app.kubernetes.io/part-of: gitops-demo
spec:
  project: default
  source:
    repoURL: https://github.com/AliyaSag/DevOps-Core-Course.git
    targetRevision: lab13
    path: k8s/python-app
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
