apiVersion: v1
kind: Service

metadata:
  name: {{ include "python-app.headlessServiceName" . }}

spec:
  clusterIP: None

  selector:
    app: python-app

  ports:
    - port: {{ .Values.headlessService.port }}
      targetPort: {{ .Values.service.targetPort }}