replicaCount: 3

image:
  repository: aserova/devops-info-service
  tag: "v2"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  targetPort: 5000

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

secret:
  enabled: true
  name: ""
  username: "placeholder-user"
  password: "placeholder-password"

serviceAccount:
  create: true
  name: ""

vault:
  enabled: false
  role: "devops-app"
  secretPath: "secret/data/myapp/config"