replicaCount: 3

image:
  repository: aserova/devops-info-service
  tag: "v3"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  targetPort: 5000

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

secret:
  enabled: true
  name: ""
  username: "bluegreen-user"
  password: "bluegreen-password"

serviceAccount:
  create: true
  name: ""

vault:
  enabled: false
  role: "devops-app"
  secretPath: "secret/data/myapp/config"

config:
  appEnv: "bluegreen"
  logLevel: "info"

persistence:
  enabled: true
  size: 100Mi
  storageClass: ""

rollout:
  strategy: blueGreen
