{
 "title": "devops lab8",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "request rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[5m])) by (endpoint)"
    }
   ]
  },
  {
   "title": "error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{status_code=~\"[45]..\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "status code distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (status_code) (rate(http_requests_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "latency heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "arcsec" } },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_bucket[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "p95 Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "active requests",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "http_requests_in_progress", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "service health",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"app\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}