apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "info-service.fullname" . }}-env
  labels:
    {{- include "info-service.labels" . | nindent 4 }}
data:
  APP_ENV: {{ .Values.config.environment | quote }}
  LOG_LEVEL: {{ .Values.config.logLevel | quote }}
  APP_NAME: {{ .Values.config.appName | quote }}
