apiVersion: v2
name: testiks
description: Helm chart for py web application
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - python
  - web
maintainers:
  - name: CacucoH
    email: dfffd7800@gmail.com
