web_app_image: "thevex/simple-app:latest"
web_app_container_name: "simple-app"
web_app_port: 8000
web_app_internal_port: 8000
web_app_restart_policy: "unless-stopped"

web_app_wipe: false
web_app_wipe_remove_image: false
web_app_env:
  ENVIRONMENT: "production"
  LOG_LEVEL: "info"
