#!/bin/bash

# Lab 05: Ansible Setup Script
# This script helps users configure their environment for deploying Ansible playbooks

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

echo "════════════════════════════════════════════════════════"
echo "  Lab 05: Ansible Infrastructure Configuration Setup"
echo "════════════════════════════════════════════════════════"
echo ""

# Check if .env already exists
if [ -f .env ]; then
    echo "⚠️  .env file already exists!"
    read -p "Do you want to reconfigure it? (y/N) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Using existing .env file"
        source load_env.sh
        exit 0
    fi
fi

echo "📝 Setting up Ansible configuration..."
echo ""

# Docker Hub Credentials
echo "🐳 Docker Hub Configuration"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
read -p "Enter Docker Hub username: " docker_username
read -sp "Enter Docker Hub password (will not be echoed): " docker_password
echo ""
echo ""

# VM Configuration
echo "🖥️  VM Configuration (Yandex Cloud / Your Infrastructure)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
read -p "Enter VM IP address: " vm_ip
read -p "Enter VM username (default: ubuntu): " vm_user
vm_user=${vm_user:-ubuntu}
read -p "Enter SSH private key path (default: ~/.ssh/id_ed25519): " ssh_key
ssh_key=${ssh_key:-~/.ssh/id_ed25519}
echo ""

# Application Configuration
echo "📦 Application Configuration"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
read -p "Enter Docker image name (default: ${docker_username}/devops-info-service:latest): " app_image
app_image=${app_image:-${docker_username}/devops-info-service:latest}
read -p "Enter application name (default: devops-info-service): " app_name
app_name=${app_name:-devops-info-service}
read -p "Enter application port (default: 5000): " app_port
app_port=${app_port:-5000}
echo ""

# Create .env file
cat > .env << ENV_EOF
# Ansible Configuration - Generated by setup.sh
# $(date)

# Docker Hub Credentials
DOCKER_HUB_USERNAME=$docker_username
DOCKER_HUB_PASSWORD=$docker_password

# VM Configuration
ANSIBLE_HOST_IP=$vm_ip
ANSIBLE_USER=$vm_user
ANSIBLE_SSH_KEY=$ssh_key

# Application Configuration
APP_NAME=$app_name
APP_IMAGE=$app_image
APP_PORT=$app_port
ENV_EOF

chmod 600 .env  # Restrict permissions to owner only
echo "✅ .env file created with restricted permissions (600)"
echo ""

# Validate the configuration
echo "🔐 Validating configuration..."
source load_env.sh

echo ""
echo "✅ Setup Complete!"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Next steps:"
echo "1. Activate virtual environment:"
echo "   source ../.venv/bin/activate"
echo ""
echo "2. Run the Ansible playbook:"
echo "   ansible-playbook playbooks/site.yml -v"
echo ""
echo "3. Test the application:"
echo "   curl http://${vm_ip}:${app_port}/health"
echo ""
