replicaCount: 3

image:
  repository: daniil20xx/myapp
  tag: "latest"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080

environment: bluegreen
logLevel: warn

rollout:
  strategy: blueGreen
  analysis:
    enabled: false
  blueGreen:
    autoPromotionEnabled: false
    scaleDownDelaySeconds: 30
    previewServiceSuffix: preview
