apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ include "my-python-app.fullname" . }}-pre-install"
  labels:
    {{- include "my-python-app.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": "hook-succeeded"
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: pre-install-job
        image: busybox:latest
        command: ['sh', '-c', 'echo Pre-install task running && sleep 5 && echo Pre-install validation completed']
