{{- if and .Values.rollout.enabled (eq .Values.rollout.strategy "blueGreen") }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-python-app.fullname" . }}-preview
  labels:
    {{- include "my-python-app.labels" . | nindent 4 }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "my-python-app.selectorLabels" . | nindent 4 }}
{{- end }}
