apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: lab14-rollouts-canary
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lab14-rollouts
  template:
    metadata:
      labels:
        app: lab14-rollouts
    spec:
      containers:
        - name: app
          image: hashicorp/http-echo:0.2.3
          args:
            - "-text=Hello from canary v1"
            - "-listen=:8000"
          ports:
            - containerPort: 8000
  strategy:
    canary:
      steps:
        - setWeight: 20
        - analysis:
            templates:
              - templateName: lab14-rollouts-analysis
        - pause: {}
        - setWeight: 40
        - pause:
            duration: 30s
        - setWeight: 60
        - pause:
            duration: 30s
        - setWeight: 80
        - pause:
            duration: 30s
        - setWeight: 100
