{{- if .Values.configmap.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "devops-info-service.fullname" . }}-config
  labels:
    {{- include "devops-info-service.labels" . | nindent 4 }}
data:
  config.json: |
{{ .Files.Get "files/config.json" | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "devops-info-service.fullname" . }}-env
  labels:
    {{- include "devops-info-service.labels" . | nindent 4 }}
data:
  APP_ENV: {{ .Values.configmap.env.APP_ENV | quote }}
  LOG_LEVEL: {{ .Values.configmap.env.LOG_LEVEL | quote }}
  FEATURE_METRICS: {{ .Values.configmap.env.FEATURE_METRICS | quote }}
{{- end }}
