apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "devops-info-service.fullname" . }}
  labels:
    {{- include "devops-info-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "devops-info-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "devops-info-service.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.container.port }}
          name: {{ .Values.container.portName }}
          protocol: TCP
        env:
          {{- toYaml .Values.env | nindent 8 }}
        {{- if .Values.secrets.enabled }}
        envFrom:
          - secretRef:
              name: {{ include "devops-info-service.fullname" . }}-credentials
        {{- end }}
        {{- if .Values.configmap.enabled }}
        envFrom:
          - configMapRef:
              name: {{ include "devops-info-service.fullname" . }}-env
        {{- end }}
        env:
          - name: DATA_DIR
            value: /data
          - name: CONFIG_DIR
            value: /config
        volumeMounts:
        - name: config-volume
          mountPath: /config
        - name: data-volume
          mountPath: /data
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        livenessProbe:
          {{- toYaml .Values.livenessProbe | nindent 10 }}
        readinessProbe:
          {{- toYaml .Values.livenessProbe | nindent 10 }}
      volumes:
      - name: config-volume
        configMap:
          name: {{ include "devops-info-service.fullname" . }}-config
      - name: data-volume
      {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ include "devops-info-service.fullname" . }}-data
      {{- else }}
        emptyDir: {}
      {{- end }}