<<<<<<< Updated upstream
workload:
  type: rollout
=======
statefulset:
  enabled: false
>>>>>>> Stashed changes

rollout:
  strategy: blueGreen
  blueGreen:
    autoPromotionEnabled: false
    autoPromotionSeconds: null

service:
  type: ClusterIP
  nodePort: null
  preview:
    enabled: true
    suffix: preview
    type: ClusterIP
