nameOverride: ""
fullnameOverride: ""

global:
  partOf: devops-core-course

app:
  label: devops-info
  component: web

replicaCount: 3
revisionHistoryLimit: 5
progressDeadlineSeconds: 600
minReadySeconds: 5

image:
  repository: sofiakulagina/devops-info
  tag: lab2
  pullPolicy: IfNotPresent

imagePullSecrets: []

container:
  port: 5002

serviceAccount:
  create: false
  automount: true
  annotations: {}
  name: ""

service:
  enabled: true
  type: NodePort
  port: 80
  targetPort: http
  nodePort: 30082

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0

rollout:
  enabled: false
  strategy: canary
  canary:
    steps:
      - setWeight: 20
      - pause: {}
      - setWeight: 40
      - pause:
          duration: 30s
      - setWeight: 60
      - pause:
          duration: 30s
      - setWeight: 80
      - pause:
          duration: 30s
      - setWeight: 100
  blueGreen:
    autoPromotionEnabled: false
    scaleDownDelaySeconds: 30
  analysis:
    enabled: false
    url: ""
    interval: 10s
    count: 3
    failureLimit: 1
    successCondition: result == "healthy"

terminationGracePeriodSeconds: 30

podAnnotations: {}
podLabels: {}

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

env:
  - name: HOST
    value: "0.0.0.0"
  - name: PORT
    value: "5002"
  - name: CONFIG_PATH
    value: /config/config.json
  - name: VISITS_FILE
    value: /data/visits
  - name: APP_ENV
    value: helm
  - name: APP_REVISION
    value: v2

config:
  enabled: true
  file:
    enabled: true
    mountPath: /config
    fileName: config.json
    applicationName: devops-info-service
    environment: dev
    featureFlags:
      visitsCounter: true
      configHotReload: true
    settings:
      logFormat: json
      storagePath: /data/visits
  env:
    enabled: true
    data:
      APP_MODE: configmap
      LOG_LEVEL: info
      FEATURE_PROFILE: persistence
      FEATURE_RUNTIME_CONFIG: enabled

secret:
  enabled: true
  create: true
  name: ""
  type: Opaque
  annotations: {}
  labels: {}
  injectAsEnvFrom: true
  stringData:
    username: placeholder-user
    password: placeholder-password

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

startupProbe:
  httpGet:
    path: /health
    port: http
  failureThreshold: 12
  periodSeconds: 5

livenessProbe:
  httpGet:
    path: /health
    port: http
  periodSeconds: 10
  timeoutSeconds: 2
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /health
    port: http
  periodSeconds: 5
  timeoutSeconds: 2
  failureThreshold: 3

nodeSelector: {}
tolerations: []
affinity: {}

persistence:
  enabled: false
  existingClaim: ""
  accessMode: ReadWriteOnce
  size: 100Mi
  storageClass: ""
  mountPath: /data

vault:
  enabled: false
  authPath: auth/kubernetes
  role: devops-info-role
  secretPath: secret/data/devops-info/config
  fileName: app-config.txt
  injectCommand: ""
  agentPrePopulateOnly: false
  template: |
    {{- with secret "secret/data/devops-info/config" -}}
    username={{ .Data.data.username }}
    password={{ .Data.data.password }}
    {{- end -}}

hookJobs:
  enabled: true
  image: busybox:1.36
  ttlSecondsAfterFinished: 30
  observationDelaySeconds: 10
  preInstall:
    enabled: true
    weight: -5
  postInstall:
    enabled: true
    weight: 5
    path: /health
    retries: 5
    retrySleepSeconds: 5
