{{- if .Values.hooks.preInstall.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ include "devops-info.fullname" . }}-pre-install"
  labels:
    {{- include "devops-info.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "{{ .Values.hooks.preInstall.weight }}"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
spec:
  template:
    metadata:
      labels:
        {{- include "devops-info.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      containers:
        - name: pre-install-check
          image: {{ .Values.hooks.image | quote }}
          command:
            - sh
            - -c
            - {{ printf "echo %s" .Values.hooks.preInstall.message | quote }}
{{- end }}
