name: Ansible Deployment

# another one
on:
  push:
    branches: [ main, master, lab06 ]
    paths:
      - 'ansible/**'
      - '.github/workflows/ansible-deploy.yml'
      - '!ansible/docs/**'
  pull_request:
    branches: [ main, master, lab06 ]
    paths:
      - 'ansible/**'
      - '.github/workflows/ansible-deploy.yml'
      - '!ansible/docs/**'
  workflow_dispatch:

jobs:
  ci:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('ansible/requirements-ci.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Create venv + install tools
        run: |
          python3 -m venv .venv
          . .venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r ansible/requirements-ci.txt
          ansible-galaxy collection install community.docker

      - name: Create vault password file for CI
        run: |
          echo "${{ secrets.ANSIBLE_VAULT_PASSWORD }}" > ansible/.vault_pass
          chmod 600 ansible/.vault_pass

      - name: Lint
        run: |
          . .venv/bin/activate
          cd ansible
          ANSIBLE_CONFIG="$PWD/ansible.cfg" \
          ANSIBLE_ROLES_PATH="$PWD/roles" \
          ansible-lint playbooks/*.yml roles/

      - name: Deploy
        run: |
          . .venv/bin/activate
          cd ansible
          ANSIBLE_CONFIG="$PWD/ansible.cfg" \
          ANSIBLE_ROLES_PATH="$PWD/roles" \
          ansible-playbook -i inventory/hosts.ini playbooks/deploy.yml \
            --vault-password-file .vault_pass

      - name: Verify
        run: |
          curl -fsS http://127.0.0.1:5000/health
          curl -fsS http://172.21.112.1:5000/health
