name: Go CI + Docker Build + Coverage

on:
  push:
    paths:
      - 'app_go/**'
      - '.github/workflows/go-ci.yml'
  pull_request:
    paths:
      - 'app_go/**'

jobs:
  build-test-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.25

      - name: Enable Go modules
        run: go env -w GO111MODULE=on

      - name: Cache Go modules and binaries
        uses: actions/cache@v3
        with:
          path: |
            ${{ env.GOPATH }}/pkg/mod
            ${{ env.GOPATH }}/bin
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install revive linter if not cached
        run: |
          if [ ! -f "${GOPATH}/bin/revive" ]; then
            go install github.com/mgechev/revive@latest
          fi

      - name: Run linter
        run: revive -formatter stylish ./...
        working-directory: app_go
        env:
          PATH: ${{ env.GOPATH }}/bin:${{ env.PATH }}

      - name: Run tests with coverage
        working-directory: app_go
        run: go test ./... -v -coverprofile=coverage.out

      - name: Verify coverage threshold
        working-directory: app_go
        run: |
          COVERAGE=$(go tool cover -func=coverage.out | grep total: | awk '{print substr($3, 1, length($3)-1)}')
          echo "Coverage is $COVERAGE%"
          THRESHOLD=40
          if (( $(echo "$COVERAGE < $THRESHOLD" | bc -l) )); then
            echo "Coverage $COVERAGE% is below threshold $THRESHOLD%"
            exit 1
          fi
        # theshold 40 is optimal for my tests

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./app_go/coverage.out
          flags: go
          name: go-coverage
          fail_ci_if_error: true
          root_dir: app_go

  docker-build:
    runs-on: ubuntu-latest
    needs: build-test-coverage

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          IMAGE_NAME=sfedbro/app_go
          VERSION=$(date +'%Y.%m')
          docker build -t $IMAGE_NAME:$VERSION -t $IMAGE_NAME:latest ./app_go
