apiVersion: v1
kind: Secret
metadata:
  name: {{ include "simple-app.fullname" . }}-secret
  labels:
    {{- include "simple-app.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.secrets.username | b64enc | quote }}
  password: {{ .Values.secrets.password | b64enc | quote }}